### ISSUE TITLE
Uploading rocks

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/moon-sand#1]
This line: https://github.com/lunarmodules/moon-sand/blob/549d9518f9a5a66f7166787888bae7f8ba339d5b/.github/workflows/deploy.yml#L61

There is a difference between tagged versions and development rocks.

1. The tagged versions should never be uploaded with `--force`, if they change the author should increment the rockspec revision. And if he/she doesn't, then I think it should fail to upload.

2. The dev versions (`dev`, `scm` and the likes instead of `2.3.1` for example) should have the flag `--skip-pack` to only upload the `rockspec`, but not the `rock` file, since it is a moving target.

3. **Arbitrary**: the dev versions should be uploaded using `--force` because imho adding rockspec revisions doesn't make sense, since the underlying code fetched from a repo is a moving target. Maybe @hishamhm has some thoughts on this.

**Comment by alerque** [comment]
> The tagged versions should never be uploaded with --force, 

Completely agree. I have some split workflows that handle SCM & tagged differently but they are super wordy. I started with a joined one here and am looking into how to setup Actions new reusable worflows thing to handle the differences between the two. Also for PR build checks vs. push to master that deploys.

> The dev versions should have the flag --skip-pack

Roger that.

> the dev versions should be uploaded using --force

I agree. Also by changing the rockspec versions on the dev/scm rockspec you make it hard to access using tooling other than via luarocks because the filename is a moving target. One could perhaps bump the rockrel on pushes to luarocks if that was important, but in the repository it should just be a moving target (at least as long as the filename has the rockrel in it).

**Comment by alerque** [comment]
All three of these points are implemented. Tweaks may need to be made for different repos but it works for the layout I use (SCM rockspec in root, all tagged ones in rockspecs dir).
